spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://localhost:5440/${DB_NAME:test_db}
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: order_db
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: public
    default-schema: order_db
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

#    properties:
#      security.protocol: SASL_PLAINTEXT
#      sasl.mechanism: PLAIN
#      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER:user1}" password="${KAFKA_PASSWORD}";

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.binarysimple.order.saga.events,ru.binarysimple.order.dto.*, ru.binarysimple.order.model.*

server:
  port: 8080

endpoints:
  api-gateway: http://localhost:8090
  users-service: http://localhost:8100
  billing-service: http://localhost:8110

logging:
  level:
    ru.binarysimple: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: WARN
    io.swagger: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus
  endpoint:
    health:
      show-details: always
      exclude: kafka
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

info:
  app:
    name: "Order Service"

app:
  kafka:
    topics:
      order-events: notification.events.order
  saga:
    retry-max-count: 3
    recover-interval: 300000
  outbox:
    retry-max-count: 3
    send-timeout-seconds: 5
    interval: 5000